on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check expressjs site links
    steps:
      - name: check links
        uses: jonchurch/express-link-check
